import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Providers } from "./providers";
import { ConnectButton } from "./components/ConnectButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <Providers>
          <header className="w-full border-b border-white/10 p-4 flex justify-between items-center glass-panel rounded-none">
            <h1 className="text-xl font-bold text-gradient">LAWP Protocol</h1>
            <ConnectButton />
          </header>
          <main className="flex-1 max-w-7xl w-full mx-auto p-6 md:p-12">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
